### ISSUE TITLE
STEAM創客具體項目網址分享

### ISSUE THREAD

**Issue by ghost** [steam-maker/steam-maker-forum#2]
我們的論壇是幫助大家集思廣益，突破理論和口號階段。歡迎大家提出實際問題，暢所欲言，共同探索具體可行的行動方案。

歡迎大家積極參與。分享經驗。

**Comment by bjgaokai** [comment]
我始终觉得stem和创客放在一起特别合适。两者刚好相互支撑，以创客的内容作为stem的载体，以stem做创客的理论支持。这样在国内跟领导说的时候将两个热门词汇放在一起，更容易接受。

**Comment by ghost** [comment]
@bjgaokai 

根據其定義，「熱門」很快也就會變成「冷門」。我們可以利用熱門跟風借力擴大影響，但是也要看看長遠結果，孩子的青春很寶貴，不是流行語的試驗品。

我們不能閉門造車，紙上談兵，要在具體項目結果和數據的基礎上再進行客觀分析。要把科學方法用於創客教育實踐中。

**Comment by ghost** [comment]
這個討論區的主要目的就是讓大家分享自己做的有關項目的信息和連結。目的是互相學習而不是推銷產品。

歡迎踴躍參與。

**Comment by bjgaokai** [comment]
科技教育一直不太受关注，近两年借着创客和国家经济发展转型，从政策上开始重视了，所以我们要借势。

**Comment by ghost** [comment]
@bjgaokai 

完全同意，真正的借勢只停留在[文字遊戲](https://github.com/steam-maker/steam-maker-forum/issues/3)一層是远远不夠的，這就是為甚麼我們要開這個論壇，把[Vannevar Bush](https://www.digital-message.com/learn/as_we_may_think)，[J. C. R. Licklider](https://www.digital-message.com/learn/licklider/licklider.pdf)， [Alan Kay](https://www.digital-message.com/learn/STEM/hc_what_Is_a_dynabook.pdf)等科技政策和教育研究方面的先驅者们的经验和思想與國內有識之士分享。

希望得到大家的積極參與和支持。

**Comment by digital-message** [comment]
很多事情保留一些時間和空間的距離反而看得更清楚。

> 不識廬山真面目，只緣身在此山中

**Comment by ghost** [comment]
很多事情保留一些時間和空間的距離反而看得更清楚。

> 不識廬山真面目，只緣身在此山中

**Comment by ghost** [comment]
請在這裡介紹你們想和大家分享的項目。網站，微博，微信平台都歡迎。

**Comment by ghost** [comment]
这是一个贴链接的例子：2016 中国创客教育http://m.eqxiu.com/s/Xmv0Patl

**Comment by ghost** [comment]
[2016年《数字教育》征稿启事](http://mp.weixin.qq.com/s?__biz=MzA4ODc1NDU2MQ==&mid=403207543&idx=1&sn=d345efc0b0269980ca8ca1d43b6b1fa7&scene=1&srcid=0402NuZvVhG2jbiQ8stRoLQD&from=groupmessage&isappinstalled=0#wechat_redirect)
